version: '2.3'

services:
  nemo-eva:
    image: jstriebel/nemo-eva
    build:
      context: .
      target: nemo-eva
    command: make
    environment:
      - DISPLAY=:99
      - DATA_PATH=${DATA_PATH:-/data/}
    ports:
      - "8888:8888"

  dev:
    image: jstriebel/nemo-eva-dev
    extends: nemo-eva
    command: sh
    build:
      context: .
      target: nemo-eva-dev

  dev-local:
    extends: dev
    volumes:
      - "./data:/data"
      - "./data-paper:/data-paper"
      - "./src:/src:ro"
